version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - mern-network

  backend1:
    build:
      context: ./backend
    container_name: backend1
    environment:
      - PORT=5000
    networks:
      - mern-network

  backend2:
    build:
      context: ./backend
    container_name: backend2
    environment:
      - PORT=5000
    networks:
      - mern-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend1
      - backend2
    networks:
      - mern-network

networks:
  mern-network:
